name: multiplayer-phase-10

services:
  player-db:
    image: postgres:latest
    restart: no
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PLAYER_DB_USER} -d ${PLAYER_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - player-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PLAYER_DB_NAME}
      POSTGRES_USER: ${PLAYER_DB_USER}
      POSTGRES_PASSWORD: ${PLAYER_DB_PASSWORD}

  game-db:
    image: postgres:latest
    restart: no
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${GAME_DB_USER} -d ${GAME_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - game-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${GAME_DB_USER}
      POSTGRES_PASSWORD: ${GAME_DB_PASSWORD}
      POSTGRES_DB: ${GAME_DB_NAME}

  shared-cache:
    image: redis:latest
    restart: no
    ports:
      - "6379:6379"
    volumes:
      - shared-cache-data:/data
  
  gateway:
    build: ./services/multiplayer-phase-10-gateway
    # depends_on:
      # service-discovery:
        # condition: service_healthy
    ports:
      - "3000:3000"

  service-discovery:
    build: ./services/multiplayer-phase-10-service-discovery
    ports:
      - "3001:3001"

  game-service:
    depends_on:
      game-db:
        condition: service_healthy
      # service-discovery:
        # condition: service_healthy
    build: ./services/multiplayer-phase-10-game-service
    ports:
      - "3030:3030"

  player-service:
    depends_on:
      player-db:
        condition: service_healthy
      # service-discovery:
        # condition: service_healthy
    build: ./services/multiplayer-phase-10-player-service
    ports:
      - "5000:5000"


volumes:
  player-db-data:
  game-db-data:
  shared-cache-data: